name: Déploiement cPanel via FTP

on:
  push:
    branches:
      - main  # Déclenche le déploiement lors d'un push sur la branche main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Récupération du code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 📂 Déploiement via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSW }}
        # Dossier local à envoyer (. pour tout le projet)
        local-dir: ./
        # Dossier distant cible sur ton serveur
        server-dir: /home/sc4marvensg/public_html/rhxtimes.com/
        # Fichiers et dossiers à ne pas envoyer
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env
          README.md
